# Character-Level LSTM in PyTorch

In this notebook, I'll construct a character-level LSTM with PyTorch. The network will train character by character on some text, then generate new text character by character. As an example, I will train on Anna Karenina. **This model will be able to generate new text based on the text from the book!**

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

First let's load in our required resources for data loading and model creation.

In [1]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

## Load in Data

Then, we'll load the Anna Karenina text file and convert it into integers for our network to use. 

In [2]:
# open text file and read in data as `text`
with open('data/anna.txt', 'r') as f:
    text = f.read()

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

### Tokenization

In the cells, below, I'm creating a couple of **dictionaries** to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [4]:
# encode the text and map each character to an integer and vice versa

# we create two dictionaries:
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

# encode the text
encoded = np.array([char2int[ch] for ch in text])

And we can see those same characters from above, encoded as integers.

In [5]:
encoded[:100]

array([49, 37, 17, 25, 75,  4, 63, 41, 73, 23, 23, 23, 59, 17, 25, 25, 44,
       41, 31, 17, 32, 68, 33, 68,  4, 66, 41, 17, 63,  4, 41, 17, 33, 33,
       41, 17, 33, 68, 24,  4, 81, 41,  4, 57,  4, 63, 44, 41, 52, 60, 37,
       17, 25, 25, 44, 41, 31, 17, 32, 68, 33, 44, 41, 68, 66, 41, 52, 60,
       37, 17, 25, 25, 44, 41, 68, 60, 41, 68, 75, 66, 41, 22, 29, 60, 23,
       29, 17, 44, 30, 23, 23,  3, 57,  4, 63, 44, 75, 37, 68, 60])

## Pre-processing the data

As you can see in our char-RNN image above, our LSTM expects an input that is **one-hot encoded** meaning that each character is converted into an integer (via our created dictionary) and *then* converted into a column vector where only it's corresponding integer index will have the value of 1 and the rest of the vector will be filled with 0's. Since we're one-hot encoding the data, let's make a function to do that!


In [6]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [7]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


In [8]:
print(one_hot.shape)

(1, 3, 8)


## Making training mini-batches


To train on this data, we also want to create mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>

In this example, we'll take the encoded characters (passed in as the `arr` parameter) and split them into multiple sequences, given by `batch_size`. Each of our sequences will be `seq_length` long.

### Creating Batches

**1. The first thing we need to do is discard some of the text so we only have completely full mini-batches. **

Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences in a batch) and $M$ is the seq_length or number of time steps in a sequence. Then, to get the total number of batches, $K$, that we can make from the array `arr`, you divide the length of `arr` by the number of characters per batch. Once you know the number of batches, you can get the total number of characters to keep from `arr`, $N * M * K$.

**2. After that, we need to split `arr` into $N$ batches. ** 

You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences in a batch, so let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$.

**3. Now that we have this array, we can iterate through it to get our mini-batches. **

The idea is each batch is a $N \times M$ window on the $N \times (M * K)$ array. For each subsequent batch, the window moves over by `seq_length`. We also want to create both the input and target arrays. Remember that the targets are just the inputs shifted over by one character. The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of tokens in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `seq_length` wide.

> **TODO:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [9]:
def get_batches(arr, batch_size, seq_length):
    '''Create a generator that returns batches of size
       batch_size x seq_length from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       batch_size: Batch size, the number of sequences per batch
       seq_length: Number of encoded chars in a sequence
    '''
    
    ## TODO: Get the number of batches we can make
    n_batches = len(arr) // batch_size
    
    ## TODO: Keep only enough characters to make full batches
    arr = arr[:n_batches*batch_size]
    
    ## TODO: Reshape into batch_size rows
    arr = arr.reshape(batch_size, -1)
    
    ## TODO: Iterate over the batches using a window of size seq_length
    # Here we are creating non-overlapping sequences
    # 1,2,3,4,5,6
    # n-> 0, , seq_len = 3
    # In my apporach, I am breaking continuity of the sequence whereas in the solution
    # It preserves the continuity
    for n in range(0, arr.shape[1]-seq_length-1, seq_length):
        # The features
        x = arr[:,n:n+seq_length]
        # The targets, shifted by one
        y = arr[:,n+1:n+seq_length+1]
        yield x, y

### Test Your Implementation

Now I'll make some data sets and we can check out what's going on as we batch data. Here, as an example, I'm going to use a batch size of 8 and 50 sequence steps.

In [10]:
batches = get_batches(encoded, 8, 50)
x, y = next(batches)

In [11]:
# printing out the first 10 items in a sequence
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[49 37 17 25 75  4 63 41 73 23]
 [60 41 75 37 17 75 41 17 75 75]
 [22 63 41 17 41 31 22  4 42 41]
 [48 37 68  4 31 41 75 37 22 52]
 [41 75  4 17 63 55 66 75 17 68]
 [53 41 17 60 17 33 44 66 68 66]
 [68 53 41 75 37 17 75 41 26 22]
 [41 71 75 37  4 44 71 41 48 17]]

y
 [[37 17 25 75  4 63 41 73 23 23]
 [41 75 37 17 75 41 17 75 75 63]
 [63 41 17 41 31 22  4 42 41 37]
 [37 68  4 31 41 75 37 22 52 16]
 [75  4 17 63 55 66 75 17 68 60]
 [41 17 60 17 33 44 66 68 66 42]
 [53 41 75 37 17 75 41 26 22 33]
 [71 75 37  4 44 71 41 48 17 60]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[25  8 60 11 45 27 28 73  1  2]
 [17  7 20 73 45  8 60 45 73 60]
 [27 20 80 73  7 28 73 60 73 65]
 [17 73 45  8 27 73 66  8 46 27]
 [73 17 60 12 73  8 27 28 73 45]
 [66 64 17 17 46  7 20 73 60 20]
 [73 76 20 20 60 73  8 60 80 73]
 [47 35 43  7 20 17 24 50 37 73]]

y
 [[ 8 60 11 45 27 28 73  1  2  2]
 [ 7 20 73 45  8 60 45 73 60 45]
 [20 80 73  7 28 73 60 73 65  7]
 [73 45  8 27 73 66  8 46 27 65]
 [17 60 12 73  8 27 28 73 45 27]
 [64 17 17 46  7 20 73 60 20 80]
 [76 20 20 60 73  8 60 80 73 17]
 [35 43  7 20 17 24 50 37 73 36]]
 ```
 although the exact numbers may be different. Check to make sure the data is shifted over one step for `y`.

---
## Defining the network with PyTorch

Below is where you'll define the network.

<img src="assets/charRNN.png" width=500px>

Next, you'll use PyTorch to define the architecture of the network. We start by defining the layers and operations we want. Then, define a method for the forward pass. You've also been given a method for predicting characters.

### Model Structure

In `__init__` the suggested structure is as follows:
* Create and store the necessary dictionaries (this has been done for you)
* Define an LSTM layer that takes as params: an input size (the number of characters), a hidden layer size `n_hidden`, a number of layers `n_layers`, a dropout probability `drop_prob`, and a batch_first boolean (True, since we are batching)
* Define a dropout layer with `drop_prob`
* Define a fully-connected layer with params: input size `n_hidden` and output size (the number of characters)
* Finally, initialize the weights (again, this has been given)

Note that some parameters have been named and given in the `__init__` function, and we use them and store them by doing something like `self.drop_prob = drop_prob`.

---
### LSTM Inputs/Outputs

You can create a basic [LSTM layer](https://pytorch.org/docs/stable/nn.html#lstm) as follows

```python
self.lstm = nn.LSTM(input_size, n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
```

where `input_size` is the number of characters this cell expects to see as sequential input, and `n_hidden` is the number of units in the hidden layers in the cell. And we can add dropout by adding a dropout parameter with a specified probability; this will automatically add dropout to the inputs or outputs. Finally, in the `forward` function, we can stack up the LSTM cells into layers using `.view`. With this, you pass in a list of cells and it will send the output of one cell into the next cell.

We also need to create an initial hidden state of all zeros. This is done like so

```python
self.init_hidden()
```

In [12]:
# check if GPU is available
train_on_gpu = torch.cuda.is_available()
if(train_on_gpu):
    print('Training on GPU!')
else: 
    print('No GPU available, training on CPU; consider making n_epochs very small.')

Training on GPU!


In [13]:
class CharRNN(nn.Module):
    
    def __init__(self, tokens, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.drop_prob = drop_prob
        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.lr = lr
        
        # creating character dictionaries
        self.chars = tokens
        self.output_len = len(self.chars)
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        ## TODO: define the layers of the model
        self.lstm = nn.LSTM(input_size=self.output_len, hidden_size = n_hidden, num_layers=n_layers,\
                            dropout=drop_prob, batch_first=True)
        self.output_layer = nn.Linear(self.n_hidden, self.output_len)
    
    def forward(self, x, hidden):
        ''' Forward pass through the network. 
            These inputs are x, and the hidden/cell state `hidden`. '''
                
        ## TODO: Get the outputs and the new hidden state from the lstm
        lstm_out, hidden = self.lstm(x, hidden)
        lstm_out = lstm_out.reshape(-1,self.n_hidden)
        # return the final output and the hidden state
        out = self.output_layer(lstm_out)
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x n_hidden,
        # Two vectors- one for long term memory and the other one for short term memory
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_(),
                      weight.new(self.n_layers, batch_size, self.n_hidden).zero_())
        
        return hidden
        

## Time to train

The train function gives us the ability to set the number of epochs, the learning rate, and other parameters.

Below we're using an Adam optimizer and cross entropy loss since we are looking at character class scores as output. We calculate the loss and perform backpropagation, as usual!

A couple of details about training: 
>* Within the batch loop, we detach the hidden state from its history; this time setting it equal to a new *tuple* variable because an LSTM has a hidden state that is a tuple of the hidden and cell states.
* We use [`clip_grad_norm_`](https://pytorch.org/docs/stable/_modules/torch/nn/utils/clip_grad.html) to help prevent exploding gradients.

In [14]:
def train(net, data, epochs=10, batch_size=10, seq_length=50, lr=0.001, clip=5, val_frac=0.1, print_every=10):
    ''' Training a network 
    
        Arguments
        ---------
        
        net: CharRNN network
        data: text data to train the network
        epochs: Number of epochs to train
        batch_size: Number of mini-sequences per mini-batch, aka batch size
        seq_length: Number of character steps per mini-batch
        lr: learning rate
        clip: gradient clipping
        val_frac: Fraction of data to hold out for validation
        print_every: Number of steps for printing training and validation loss
    
    '''
    net.train()
    
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    # create training and validation data
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    if(train_on_gpu):
        net.cuda()
    
    counter = 0
    n_chars = len(net.chars)
    for e in range(epochs):
        # initialize hidden state
        h = net.init_hidden(batch_size)
        
        for x, y in get_batches(data, batch_size, seq_length):
            counter += 1
            
            # One-hot encode our data and make them Torch tensors
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            
            if(train_on_gpu):
                inputs, targets = inputs.cuda(), targets.cuda()

            # Creating new variables for the hidden state, otherwise
            # we'd backprop through the entire training history
            h = tuple([each.data for each in h])

            # zero accumulated gradients
            # optim.zero_grad() vs net.zero_grad()
            net.zero_grad()
            
            # get the output from the model
            output, h = net(inputs, h)
            
            # calculate the loss and perform backprop
            ## output- [B*T,V], target-[B,T,V]
            loss = criterion(output, targets.view(batch_size*seq_length).long())
            loss.backward()
            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
            nn.utils.clip_grad_norm_(net.parameters(), clip)
            opt.step()
            
            # loss stats
            if counter % print_every == 0:
                # Get validation loss
                val_h = net.init_hidden(batch_size)
                val_losses = []
                net.eval()
                for x, y in get_batches(val_data, batch_size, seq_length):
                    # One-hot encode our data and make them Torch tensors
                    x = one_hot_encode(x, n_chars)
                    x, y = torch.from_numpy(x), torch.from_numpy(y)
                    
                    # Creating new variables for the hidden state, otherwise
                    # we'd backprop through the entire training history
                    val_h = tuple([each.data for each in val_h])
                    
                    inputs, targets = x, y
                    if(train_on_gpu):
                        inputs, targets = inputs.cuda(), targets.cuda()
                    output, val_h = net(inputs, val_h)
                    val_loss = criterion(output, targets.view(batch_size*seq_length).long())
                
                    val_losses.append(val_loss.item())
                
                net.train() # reset to train mode after iterationg through validation data
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))

## Instantiating the model

Now we can actually train the network. First we'll create the network itself, with some given hyperparameters. Then, define the mini-batches sizes, and start training!

In [19]:
## TODO: set your model hyperparameters
# define and print the net
n_hidden=128
n_layers=2

net = CharRNN(chars, n_hidden, n_layers)
print(net)

CharRNN(
  (lstm): LSTM(83, 128, num_layers=2, batch_first=True, dropout=0.5)
  (output_layer): Linear(in_features=128, out_features=83, bias=True)
)


### Set your training hyperparameters!

In [20]:
batch_size = 64
# Average word length is 4, It is good if we want to learn the next character given a singel word
# but the next character may depend upon the whole sentence
# The average sentence length is 15-20. Which is good if we want to learn next character given the sentence
# Let's take a middle gorund 10
seq_length = 10
n_epochs =  20# start small if you are just testing initial behavior

# train the model
train(net, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, lr=0.001, print_every=10)

Epoch: 1/20... Step: 10... Loss: 4.1746... Val Loss: 4.0260
Epoch: 1/20... Step: 20... Loss: 3.1985... Val Loss: 3.1771
Epoch: 1/20... Step: 30... Loss: 3.1682... Val Loss: 3.1466
Epoch: 1/20... Step: 40... Loss: 3.0634... Val Loss: 3.1352
Epoch: 1/20... Step: 50... Loss: 3.0565... Val Loss: 3.1325
Epoch: 1/20... Step: 60... Loss: 3.1415... Val Loss: 3.1323
Epoch: 1/20... Step: 70... Loss: 3.1558... Val Loss: 3.1316
Epoch: 1/20... Step: 80... Loss: 3.0819... Val Loss: 3.1312
Epoch: 1/20... Step: 90... Loss: 3.0850... Val Loss: 3.1291
Epoch: 1/20... Step: 100... Loss: 3.1406... Val Loss: 3.1305
Epoch: 1/20... Step: 110... Loss: 3.0404... Val Loss: 3.1279
Epoch: 1/20... Step: 120... Loss: 3.0680... Val Loss: 3.1297
Epoch: 1/20... Step: 130... Loss: 3.1020... Val Loss: 3.1296
Epoch: 1/20... Step: 140... Loss: 3.1149... Val Loss: 3.1288
Epoch: 1/20... Step: 150... Loss: 3.0521... Val Loss: 3.1336
Epoch: 1/20... Step: 160... Loss: 3.1481... Val Loss: 3.1312
Epoch: 1/20... Step: 170... Loss:

Epoch: 1/20... Step: 1350... Loss: 2.1975... Val Loss: 2.2360
Epoch: 1/20... Step: 1360... Loss: 2.2813... Val Loss: 2.2394
Epoch: 1/20... Step: 1370... Loss: 2.2583... Val Loss: 2.2255
Epoch: 1/20... Step: 1380... Loss: 2.1590... Val Loss: 2.2176
Epoch: 1/20... Step: 1390... Loss: 2.1874... Val Loss: 2.2197
Epoch: 1/20... Step: 1400... Loss: 2.2630... Val Loss: 2.2166
Epoch: 1/20... Step: 1410... Loss: 2.1361... Val Loss: 2.2085
Epoch: 1/20... Step: 1420... Loss: 2.1374... Val Loss: 2.2057
Epoch: 1/20... Step: 1430... Loss: 2.1584... Val Loss: 2.2053
Epoch: 1/20... Step: 1440... Loss: 2.2272... Val Loss: 2.2082
Epoch: 1/20... Step: 1450... Loss: 2.1139... Val Loss: 2.2015
Epoch: 1/20... Step: 1460... Loss: 2.1514... Val Loss: 2.1972
Epoch: 1/20... Step: 1470... Loss: 2.1635... Val Loss: 2.1916
Epoch: 1/20... Step: 1480... Loss: 2.1057... Val Loss: 2.1942
Epoch: 1/20... Step: 1490... Loss: 2.1343... Val Loss: 2.1898
Epoch: 1/20... Step: 1500... Loss: 2.1980... Val Loss: 2.1862
Epoch: 1

Epoch: 1/20... Step: 2680... Loss: 1.8392... Val Loss: 1.9488
Epoch: 1/20... Step: 2690... Loss: 1.8610... Val Loss: 1.9452
Epoch: 1/20... Step: 2700... Loss: 1.9363... Val Loss: 1.9478
Epoch: 1/20... Step: 2710... Loss: 1.8423... Val Loss: 1.9455
Epoch: 1/20... Step: 2720... Loss: 1.9405... Val Loss: 1.9469
Epoch: 1/20... Step: 2730... Loss: 1.9751... Val Loss: 1.9411
Epoch: 1/20... Step: 2740... Loss: 1.8825... Val Loss: 1.9460
Epoch: 1/20... Step: 2750... Loss: 1.8500... Val Loss: 1.9382
Epoch: 1/20... Step: 2760... Loss: 1.8501... Val Loss: 1.9384
Epoch: 1/20... Step: 2770... Loss: 1.8629... Val Loss: 1.9364
Epoch: 1/20... Step: 2780... Loss: 1.8410... Val Loss: 1.9372
Epoch: 1/20... Step: 2790... Loss: 1.8819... Val Loss: 1.9336
Epoch: 2/20... Step: 2800... Loss: 1.9112... Val Loss: 1.9354
Epoch: 2/20... Step: 2810... Loss: 1.8463... Val Loss: 1.9279
Epoch: 2/20... Step: 2820... Loss: 1.8538... Val Loss: 1.9288
Epoch: 2/20... Step: 2830... Loss: 1.8163... Val Loss: 1.9276
Epoch: 2

Epoch: 2/20... Step: 4010... Loss: 1.7421... Val Loss: 1.7951
Epoch: 2/20... Step: 4020... Loss: 1.7437... Val Loss: 1.7945
Epoch: 2/20... Step: 4030... Loss: 1.7625... Val Loss: 1.7969
Epoch: 2/20... Step: 4040... Loss: 1.8413... Val Loss: 1.7960
Epoch: 2/20... Step: 4050... Loss: 1.8277... Val Loss: 1.7978
Epoch: 2/20... Step: 4060... Loss: 1.7757... Val Loss: 1.7982
Epoch: 2/20... Step: 4070... Loss: 1.7097... Val Loss: 1.7909
Epoch: 2/20... Step: 4080... Loss: 1.6910... Val Loss: 1.7898
Epoch: 2/20... Step: 4090... Loss: 1.6727... Val Loss: 1.7982
Epoch: 2/20... Step: 4100... Loss: 1.6512... Val Loss: 1.7916
Epoch: 2/20... Step: 4110... Loss: 1.7748... Val Loss: 1.7925
Epoch: 2/20... Step: 4120... Loss: 1.7668... Val Loss: 1.7887
Epoch: 2/20... Step: 4130... Loss: 1.5774... Val Loss: 1.7885
Epoch: 2/20... Step: 4140... Loss: 1.7715... Val Loss: 1.7891
Epoch: 2/20... Step: 4150... Loss: 1.8255... Val Loss: 1.7888
Epoch: 2/20... Step: 4160... Loss: 1.8140... Val Loss: 1.7854
Epoch: 2

Epoch: 2/20... Step: 5340... Loss: 1.6160... Val Loss: 1.7195
Epoch: 2/20... Step: 5350... Loss: 1.7294... Val Loss: 1.7178
Epoch: 2/20... Step: 5360... Loss: 1.5604... Val Loss: 1.7169
Epoch: 2/20... Step: 5370... Loss: 1.5969... Val Loss: 1.7157
Epoch: 2/20... Step: 5380... Loss: 1.6557... Val Loss: 1.7121
Epoch: 2/20... Step: 5390... Loss: 1.6130... Val Loss: 1.7137
Epoch: 2/20... Step: 5400... Loss: 1.6353... Val Loss: 1.7172
Epoch: 2/20... Step: 5410... Loss: 1.6657... Val Loss: 1.7126
Epoch: 2/20... Step: 5420... Loss: 1.6501... Val Loss: 1.7148
Epoch: 2/20... Step: 5430... Loss: 1.7045... Val Loss: 1.7125
Epoch: 2/20... Step: 5440... Loss: 1.5514... Val Loss: 1.7116
Epoch: 2/20... Step: 5450... Loss: 1.6488... Val Loss: 1.7069
Epoch: 2/20... Step: 5460... Loss: 1.5214... Val Loss: 1.7099
Epoch: 2/20... Step: 5470... Loss: 1.5811... Val Loss: 1.7105
Epoch: 2/20... Step: 5480... Loss: 1.5847... Val Loss: 1.7081
Epoch: 2/20... Step: 5490... Loss: 1.6884... Val Loss: 1.7077
Epoch: 2

Epoch: 3/20... Step: 6670... Loss: 1.4911... Val Loss: 1.6646
Epoch: 3/20... Step: 6680... Loss: 1.5787... Val Loss: 1.6625
Epoch: 3/20... Step: 6690... Loss: 1.5963... Val Loss: 1.6654
Epoch: 3/20... Step: 6700... Loss: 1.5358... Val Loss: 1.6607
Epoch: 3/20... Step: 6710... Loss: 1.6008... Val Loss: 1.6610
Epoch: 3/20... Step: 6720... Loss: 1.6959... Val Loss: 1.6625
Epoch: 3/20... Step: 6730... Loss: 1.4680... Val Loss: 1.6621
Epoch: 3/20... Step: 6740... Loss: 1.5643... Val Loss: 1.6614
Epoch: 3/20... Step: 6750... Loss: 1.5901... Val Loss: 1.6625
Epoch: 3/20... Step: 6760... Loss: 1.4739... Val Loss: 1.6614
Epoch: 3/20... Step: 6770... Loss: 1.3987... Val Loss: 1.6625
Epoch: 3/20... Step: 6780... Loss: 1.6366... Val Loss: 1.6604
Epoch: 3/20... Step: 6790... Loss: 1.6350... Val Loss: 1.6609
Epoch: 3/20... Step: 6800... Loss: 1.6275... Val Loss: 1.6548
Epoch: 3/20... Step: 6810... Loss: 1.5980... Val Loss: 1.6560
Epoch: 3/20... Step: 6820... Loss: 1.5113... Val Loss: 1.6598
Epoch: 3

Epoch: 3/20... Step: 8000... Loss: 1.5470... Val Loss: 1.6297
Epoch: 3/20... Step: 8010... Loss: 1.5291... Val Loss: 1.6290
Epoch: 3/20... Step: 8020... Loss: 1.4755... Val Loss: 1.6317
Epoch: 3/20... Step: 8030... Loss: 1.6985... Val Loss: 1.6253
Epoch: 3/20... Step: 8040... Loss: 1.4326... Val Loss: 1.6287
Epoch: 3/20... Step: 8050... Loss: 1.5269... Val Loss: 1.6284
Epoch: 3/20... Step: 8060... Loss: 1.5685... Val Loss: 1.6259
Epoch: 3/20... Step: 8070... Loss: 1.7423... Val Loss: 1.6261
Epoch: 3/20... Step: 8080... Loss: 1.4549... Val Loss: 1.6218
Epoch: 3/20... Step: 8090... Loss: 1.6659... Val Loss: 1.6211
Epoch: 3/20... Step: 8100... Loss: 1.6484... Val Loss: 1.6200
Epoch: 3/20... Step: 8110... Loss: 1.5377... Val Loss: 1.6212
Epoch: 3/20... Step: 8120... Loss: 1.6010... Val Loss: 1.6231
Epoch: 3/20... Step: 8130... Loss: 1.6676... Val Loss: 1.6240
Epoch: 3/20... Step: 8140... Loss: 1.5911... Val Loss: 1.6232
Epoch: 3/20... Step: 8150... Loss: 1.5283... Val Loss: 1.6227
Epoch: 3

Epoch: 4/20... Step: 9330... Loss: 1.4574... Val Loss: 1.5987
Epoch: 4/20... Step: 9340... Loss: 1.5486... Val Loss: 1.6007
Epoch: 4/20... Step: 9350... Loss: 1.5643... Val Loss: 1.6018
Epoch: 4/20... Step: 9360... Loss: 1.5300... Val Loss: 1.6038
Epoch: 4/20... Step: 9370... Loss: 1.5636... Val Loss: 1.5978
Epoch: 4/20... Step: 9380... Loss: 1.5331... Val Loss: 1.5971
Epoch: 4/20... Step: 9390... Loss: 1.5384... Val Loss: 1.5982
Epoch: 4/20... Step: 9400... Loss: 1.5770... Val Loss: 1.5945
Epoch: 4/20... Step: 9410... Loss: 1.5092... Val Loss: 1.5987
Epoch: 4/20... Step: 9420... Loss: 1.3820... Val Loss: 1.5993
Epoch: 4/20... Step: 9430... Loss: 1.4713... Val Loss: 1.5976
Epoch: 4/20... Step: 9440... Loss: 1.4983... Val Loss: 1.5951
Epoch: 4/20... Step: 9450... Loss: 1.6085... Val Loss: 1.5977
Epoch: 4/20... Step: 9460... Loss: 1.5432... Val Loss: 1.5968
Epoch: 4/20... Step: 9470... Loss: 1.6591... Val Loss: 1.5933
Epoch: 4/20... Step: 9480... Loss: 1.5160... Val Loss: 1.5983
Epoch: 4

Epoch: 4/20... Step: 10650... Loss: 1.5120... Val Loss: 1.5773
Epoch: 4/20... Step: 10660... Loss: 1.5429... Val Loss: 1.5781
Epoch: 4/20... Step: 10670... Loss: 1.6407... Val Loss: 1.5781
Epoch: 4/20... Step: 10680... Loss: 1.4466... Val Loss: 1.5766
Epoch: 4/20... Step: 10690... Loss: 1.4172... Val Loss: 1.5792
Epoch: 4/20... Step: 10700... Loss: 1.5000... Val Loss: 1.5772
Epoch: 4/20... Step: 10710... Loss: 1.4857... Val Loss: 1.5757
Epoch: 4/20... Step: 10720... Loss: 1.4857... Val Loss: 1.5753
Epoch: 4/20... Step: 10730... Loss: 1.5578... Val Loss: 1.5764
Epoch: 4/20... Step: 10740... Loss: 1.5387... Val Loss: 1.5735
Epoch: 4/20... Step: 10750... Loss: 1.4809... Val Loss: 1.5759
Epoch: 4/20... Step: 10760... Loss: 1.4487... Val Loss: 1.5753
Epoch: 4/20... Step: 10770... Loss: 1.4238... Val Loss: 1.5751
Epoch: 4/20... Step: 10780... Loss: 1.4813... Val Loss: 1.5714
Epoch: 4/20... Step: 10790... Loss: 1.4762... Val Loss: 1.5729
Epoch: 4/20... Step: 10800... Loss: 1.4351... Val Loss:

Epoch: 5/20... Step: 11960... Loss: 1.3675... Val Loss: 1.5587
Epoch: 5/20... Step: 11970... Loss: 1.4168... Val Loss: 1.5571
Epoch: 5/20... Step: 11980... Loss: 1.4602... Val Loss: 1.5576
Epoch: 5/20... Step: 11990... Loss: 1.5595... Val Loss: 1.5581
Epoch: 5/20... Step: 12000... Loss: 1.5221... Val Loss: 1.5577
Epoch: 5/20... Step: 12010... Loss: 1.5121... Val Loss: 1.5612
Epoch: 5/20... Step: 12020... Loss: 1.3796... Val Loss: 1.5571
Epoch: 5/20... Step: 12030... Loss: 1.4435... Val Loss: 1.5585
Epoch: 5/20... Step: 12040... Loss: 1.4621... Val Loss: 1.5569
Epoch: 5/20... Step: 12050... Loss: 1.5420... Val Loss: 1.5548
Epoch: 5/20... Step: 12060... Loss: 1.4823... Val Loss: 1.5549
Epoch: 5/20... Step: 12070... Loss: 1.4932... Val Loss: 1.5564
Epoch: 5/20... Step: 12080... Loss: 1.3569... Val Loss: 1.5549
Epoch: 5/20... Step: 12090... Loss: 1.3771... Val Loss: 1.5573
Epoch: 5/20... Step: 12100... Loss: 1.4263... Val Loss: 1.5619
Epoch: 5/20... Step: 12110... Loss: 1.4751... Val Loss:

Epoch: 5/20... Step: 13270... Loss: 1.4740... Val Loss: 1.5472
Epoch: 5/20... Step: 13280... Loss: 1.3250... Val Loss: 1.5474
Epoch: 5/20... Step: 13290... Loss: 1.5423... Val Loss: 1.5455
Epoch: 5/20... Step: 13300... Loss: 1.4291... Val Loss: 1.5480
Epoch: 5/20... Step: 13310... Loss: 1.4936... Val Loss: 1.5452
Epoch: 5/20... Step: 13320... Loss: 1.4053... Val Loss: 1.5438
Epoch: 5/20... Step: 13330... Loss: 1.4791... Val Loss: 1.5427
Epoch: 5/20... Step: 13340... Loss: 1.4489... Val Loss: 1.5431
Epoch: 5/20... Step: 13350... Loss: 1.6740... Val Loss: 1.5444
Epoch: 5/20... Step: 13360... Loss: 1.5297... Val Loss: 1.5435
Epoch: 5/20... Step: 13370... Loss: 1.4117... Val Loss: 1.5404
Epoch: 5/20... Step: 13380... Loss: 1.4512... Val Loss: 1.5420
Epoch: 5/20... Step: 13390... Loss: 1.3270... Val Loss: 1.5414
Epoch: 5/20... Step: 13400... Loss: 1.4465... Val Loss: 1.5410
Epoch: 5/20... Step: 13410... Loss: 1.6070... Val Loss: 1.5438
Epoch: 5/20... Step: 13420... Loss: 1.5695... Val Loss:

Epoch: 6/20... Step: 14580... Loss: 1.4707... Val Loss: 1.5316
Epoch: 6/20... Step: 14590... Loss: 1.3593... Val Loss: 1.5316
Epoch: 6/20... Step: 14600... Loss: 1.4421... Val Loss: 1.5361
Epoch: 6/20... Step: 14610... Loss: 1.4157... Val Loss: 1.5342
Epoch: 6/20... Step: 14620... Loss: 1.5805... Val Loss: 1.5323
Epoch: 6/20... Step: 14630... Loss: 1.5161... Val Loss: 1.5317
Epoch: 6/20... Step: 14640... Loss: 1.5853... Val Loss: 1.5367
Epoch: 6/20... Step: 14650... Loss: 1.3615... Val Loss: 1.5310
Epoch: 6/20... Step: 14660... Loss: 1.3375... Val Loss: 1.5314
Epoch: 6/20... Step: 14670... Loss: 1.5096... Val Loss: 1.5331
Epoch: 6/20... Step: 14680... Loss: 1.4930... Val Loss: 1.5371
Epoch: 6/20... Step: 14690... Loss: 1.5377... Val Loss: 1.5360
Epoch: 6/20... Step: 14700... Loss: 1.3663... Val Loss: 1.5331
Epoch: 6/20... Step: 14710... Loss: 1.4899... Val Loss: 1.5359
Epoch: 6/20... Step: 14720... Loss: 1.4648... Val Loss: 1.5342
Epoch: 6/20... Step: 14730... Loss: 1.5408... Val Loss:

Epoch: 6/20... Step: 15890... Loss: 1.5035... Val Loss: 1.5246
Epoch: 6/20... Step: 15900... Loss: 1.5745... Val Loss: 1.5228
Epoch: 6/20... Step: 15910... Loss: 1.3969... Val Loss: 1.5250
Epoch: 6/20... Step: 15920... Loss: 1.3988... Val Loss: 1.5260
Epoch: 6/20... Step: 15930... Loss: 1.4041... Val Loss: 1.5274
Epoch: 6/20... Step: 15940... Loss: 1.3943... Val Loss: 1.5249
Epoch: 6/20... Step: 15950... Loss: 1.4579... Val Loss: 1.5270
Epoch: 6/20... Step: 15960... Loss: 1.3920... Val Loss: 1.5235
Epoch: 6/20... Step: 15970... Loss: 1.4109... Val Loss: 1.5268
Epoch: 6/20... Step: 15980... Loss: 1.4638... Val Loss: 1.5261
Epoch: 6/20... Step: 15990... Loss: 1.5408... Val Loss: 1.5280
Epoch: 6/20... Step: 16000... Loss: 1.5571... Val Loss: 1.5246
Epoch: 6/20... Step: 16010... Loss: 1.5322... Val Loss: 1.5263
Epoch: 6/20... Step: 16020... Loss: 1.3576... Val Loss: 1.5240
Epoch: 6/20... Step: 16030... Loss: 1.3172... Val Loss: 1.5255
Epoch: 6/20... Step: 16040... Loss: 1.3922... Val Loss:

Epoch: 7/20... Step: 17200... Loss: 1.4469... Val Loss: 1.5129
Epoch: 7/20... Step: 17210... Loss: 1.3880... Val Loss: 1.5129
Epoch: 7/20... Step: 17220... Loss: 1.3922... Val Loss: 1.5110
Epoch: 7/20... Step: 17230... Loss: 1.4489... Val Loss: 1.5145
Epoch: 7/20... Step: 17240... Loss: 1.3063... Val Loss: 1.5150
Epoch: 7/20... Step: 17250... Loss: 1.4567... Val Loss: 1.5153
Epoch: 7/20... Step: 17260... Loss: 1.4052... Val Loss: 1.5150
Epoch: 7/20... Step: 17270... Loss: 1.3733... Val Loss: 1.5162
Epoch: 7/20... Step: 17280... Loss: 1.4888... Val Loss: 1.5150
Epoch: 7/20... Step: 17290... Loss: 1.4249... Val Loss: 1.5184
Epoch: 7/20... Step: 17300... Loss: 1.4741... Val Loss: 1.5182
Epoch: 7/20... Step: 17310... Loss: 1.4553... Val Loss: 1.5161
Epoch: 7/20... Step: 17320... Loss: 1.3964... Val Loss: 1.5202
Epoch: 7/20... Step: 17330... Loss: 1.4695... Val Loss: 1.5217
Epoch: 7/20... Step: 17340... Loss: 1.4112... Val Loss: 1.5194
Epoch: 7/20... Step: 17350... Loss: 1.4178... Val Loss:

Epoch: 7/20... Step: 18510... Loss: 1.4155... Val Loss: 1.5063
Epoch: 7/20... Step: 18520... Loss: 1.3174... Val Loss: 1.5107
Epoch: 7/20... Step: 18530... Loss: 1.3987... Val Loss: 1.5081
Epoch: 7/20... Step: 18540... Loss: 1.4367... Val Loss: 1.5047
Epoch: 7/20... Step: 18550... Loss: 1.4810... Val Loss: 1.5034
Epoch: 7/20... Step: 18560... Loss: 1.4022... Val Loss: 1.5044
Epoch: 7/20... Step: 18570... Loss: 1.3780... Val Loss: 1.5046
Epoch: 7/20... Step: 18580... Loss: 1.4866... Val Loss: 1.5063
Epoch: 7/20... Step: 18590... Loss: 1.3935... Val Loss: 1.5043
Epoch: 7/20... Step: 18600... Loss: 1.4489... Val Loss: 1.5052
Epoch: 7/20... Step: 18610... Loss: 1.4984... Val Loss: 1.5075
Epoch: 7/20... Step: 18620... Loss: 1.4551... Val Loss: 1.5068
Epoch: 7/20... Step: 18630... Loss: 1.4452... Val Loss: 1.5074
Epoch: 7/20... Step: 18640... Loss: 1.3693... Val Loss: 1.5101
Epoch: 7/20... Step: 18650... Loss: 1.5071... Val Loss: 1.5073
Epoch: 7/20... Step: 18660... Loss: 1.4810... Val Loss:

Epoch: 8/20... Step: 19820... Loss: 1.3052... Val Loss: 1.4998
Epoch: 8/20... Step: 19830... Loss: 1.4028... Val Loss: 1.5003
Epoch: 8/20... Step: 19840... Loss: 1.4813... Val Loss: 1.5013
Epoch: 8/20... Step: 19850... Loss: 1.4126... Val Loss: 1.5050
Epoch: 8/20... Step: 19860... Loss: 1.4332... Val Loss: 1.4977
Epoch: 8/20... Step: 19870... Loss: 1.4260... Val Loss: 1.4941
Epoch: 8/20... Step: 19880... Loss: 1.3942... Val Loss: 1.4971
Epoch: 8/20... Step: 19890... Loss: 1.4404... Val Loss: 1.4964
Epoch: 8/20... Step: 19900... Loss: 1.4124... Val Loss: 1.4967
Epoch: 8/20... Step: 19910... Loss: 1.3833... Val Loss: 1.5005
Epoch: 8/20... Step: 19920... Loss: 1.5418... Val Loss: 1.4973
Epoch: 8/20... Step: 19930... Loss: 1.4948... Val Loss: 1.4949
Epoch: 8/20... Step: 19940... Loss: 1.4126... Val Loss: 1.4969
Epoch: 8/20... Step: 19950... Loss: 1.4378... Val Loss: 1.4979
Epoch: 8/20... Step: 19960... Loss: 1.4356... Val Loss: 1.4979
Epoch: 8/20... Step: 19970... Loss: 1.3990... Val Loss:

Epoch: 8/20... Step: 21130... Loss: 1.2974... Val Loss: 1.4954
Epoch: 8/20... Step: 21140... Loss: 1.3410... Val Loss: 1.4944
Epoch: 8/20... Step: 21150... Loss: 1.3413... Val Loss: 1.4949
Epoch: 8/20... Step: 21160... Loss: 1.6202... Val Loss: 1.4952
Epoch: 8/20... Step: 21170... Loss: 1.3989... Val Loss: 1.4941
Epoch: 8/20... Step: 21180... Loss: 1.3311... Val Loss: 1.4957
Epoch: 8/20... Step: 21190... Loss: 1.3702... Val Loss: 1.4969
Epoch: 8/20... Step: 21200... Loss: 1.4223... Val Loss: 1.4950
Epoch: 8/20... Step: 21210... Loss: 1.3987... Val Loss: 1.4949
Epoch: 8/20... Step: 21220... Loss: 1.3560... Val Loss: 1.4969
Epoch: 8/20... Step: 21230... Loss: 1.4528... Val Loss: 1.4944
Epoch: 8/20... Step: 21240... Loss: 1.5078... Val Loss: 1.4933
Epoch: 8/20... Step: 21250... Loss: 1.4336... Val Loss: 1.4968
Epoch: 8/20... Step: 21260... Loss: 1.3571... Val Loss: 1.4917
Epoch: 8/20... Step: 21270... Loss: 1.2914... Val Loss: 1.4904
Epoch: 8/20... Step: 21280... Loss: 1.4640... Val Loss:

Epoch: 9/20... Step: 22440... Loss: 1.3484... Val Loss: 1.4928
Epoch: 9/20... Step: 22450... Loss: 1.3265... Val Loss: 1.4924
Epoch: 9/20... Step: 22460... Loss: 1.4394... Val Loss: 1.4930
Epoch: 9/20... Step: 22470... Loss: 1.4379... Val Loss: 1.4916
Epoch: 9/20... Step: 22480... Loss: 1.4320... Val Loss: 1.4894
Epoch: 9/20... Step: 22490... Loss: 1.3476... Val Loss: 1.4924
Epoch: 9/20... Step: 22500... Loss: 1.3872... Val Loss: 1.4879
Epoch: 9/20... Step: 22510... Loss: 1.3974... Val Loss: 1.4877
Epoch: 9/20... Step: 22520... Loss: 1.4108... Val Loss: 1.4892
Epoch: 9/20... Step: 22530... Loss: 1.4231... Val Loss: 1.4914
Epoch: 9/20... Step: 22540... Loss: 1.3616... Val Loss: 1.4908
Epoch: 9/20... Step: 22550... Loss: 1.3195... Val Loss: 1.4912
Epoch: 9/20... Step: 22560... Loss: 1.4536... Val Loss: 1.4896
Epoch: 9/20... Step: 22570... Loss: 1.2680... Val Loss: 1.4910
Epoch: 9/20... Step: 22580... Loss: 1.3361... Val Loss: 1.4928
Epoch: 9/20... Step: 22590... Loss: 1.3520... Val Loss:

Epoch: 9/20... Step: 23750... Loss: 1.4410... Val Loss: 1.4854
Epoch: 9/20... Step: 23760... Loss: 1.4242... Val Loss: 1.4868
Epoch: 9/20... Step: 23770... Loss: 1.5699... Val Loss: 1.4861
Epoch: 9/20... Step: 23780... Loss: 1.4348... Val Loss: 1.4834
Epoch: 9/20... Step: 23790... Loss: 1.4344... Val Loss: 1.4839
Epoch: 9/20... Step: 23800... Loss: 1.4482... Val Loss: 1.4827
Epoch: 9/20... Step: 23810... Loss: 1.3740... Val Loss: 1.4843
Epoch: 9/20... Step: 23820... Loss: 1.2943... Val Loss: 1.4836
Epoch: 9/20... Step: 23830... Loss: 1.3413... Val Loss: 1.4836
Epoch: 9/20... Step: 23840... Loss: 1.3270... Val Loss: 1.4807
Epoch: 9/20... Step: 23850... Loss: 1.4160... Val Loss: 1.4817
Epoch: 9/20... Step: 23860... Loss: 1.2371... Val Loss: 1.4844
Epoch: 9/20... Step: 23870... Loss: 1.2852... Val Loss: 1.4858
Epoch: 9/20... Step: 23880... Loss: 1.4306... Val Loss: 1.4845
Epoch: 9/20... Step: 23890... Loss: 1.4860... Val Loss: 1.4870
Epoch: 9/20... Step: 23900... Loss: 1.2465... Val Loss:

Epoch: 9/20... Step: 25060... Loss: 1.3729... Val Loss: 1.4783
Epoch: 9/20... Step: 25070... Loss: 1.4620... Val Loss: 1.4801
Epoch: 9/20... Step: 25080... Loss: 1.3572... Val Loss: 1.4827
Epoch: 9/20... Step: 25090... Loss: 1.4011... Val Loss: 1.4801
Epoch: 9/20... Step: 25100... Loss: 1.3575... Val Loss: 1.4779
Epoch: 9/20... Step: 25110... Loss: 1.2543... Val Loss: 1.4803
Epoch: 10/20... Step: 25120... Loss: 1.7394... Val Loss: 1.4770
Epoch: 10/20... Step: 25130... Loss: 1.3551... Val Loss: 1.4815
Epoch: 10/20... Step: 25140... Loss: 1.3821... Val Loss: 1.4814
Epoch: 10/20... Step: 25150... Loss: 1.4554... Val Loss: 1.4832
Epoch: 10/20... Step: 25160... Loss: 1.4168... Val Loss: 1.4823
Epoch: 10/20... Step: 25170... Loss: 1.5336... Val Loss: 1.4813
Epoch: 10/20... Step: 25180... Loss: 1.3436... Val Loss: 1.4808
Epoch: 10/20... Step: 25190... Loss: 1.5611... Val Loss: 1.4838
Epoch: 10/20... Step: 25200... Loss: 1.3402... Val Loss: 1.4820
Epoch: 10/20... Step: 25210... Loss: 1.3423...

Epoch: 10/20... Step: 26350... Loss: 1.4130... Val Loss: 1.4776
Epoch: 10/20... Step: 26360... Loss: 1.3610... Val Loss: 1.4764
Epoch: 10/20... Step: 26370... Loss: 1.3573... Val Loss: 1.4746
Epoch: 10/20... Step: 26380... Loss: 1.4026... Val Loss: 1.4735
Epoch: 10/20... Step: 26390... Loss: 1.5190... Val Loss: 1.4747
Epoch: 10/20... Step: 26400... Loss: 1.4448... Val Loss: 1.4739
Epoch: 10/20... Step: 26410... Loss: 1.4298... Val Loss: 1.4766
Epoch: 10/20... Step: 26420... Loss: 1.5156... Val Loss: 1.4744
Epoch: 10/20... Step: 26430... Loss: 1.4520... Val Loss: 1.4726
Epoch: 10/20... Step: 26440... Loss: 1.3879... Val Loss: 1.4748
Epoch: 10/20... Step: 26450... Loss: 1.3227... Val Loss: 1.4742
Epoch: 10/20... Step: 26460... Loss: 1.2957... Val Loss: 1.4764
Epoch: 10/20... Step: 26470... Loss: 1.4301... Val Loss: 1.4741
Epoch: 10/20... Step: 26480... Loss: 1.3993... Val Loss: 1.4736
Epoch: 10/20... Step: 26490... Loss: 1.3448... Val Loss: 1.4736
Epoch: 10/20... Step: 26500... Loss: 1.3

Epoch: 10/20... Step: 27640... Loss: 1.3497... Val Loss: 1.4731
Epoch: 10/20... Step: 27650... Loss: 1.2706... Val Loss: 1.4769
Epoch: 10/20... Step: 27660... Loss: 1.3100... Val Loss: 1.4750
Epoch: 10/20... Step: 27670... Loss: 1.4219... Val Loss: 1.4755
Epoch: 10/20... Step: 27680... Loss: 1.3924... Val Loss: 1.4745
Epoch: 10/20... Step: 27690... Loss: 1.3646... Val Loss: 1.4733
Epoch: 10/20... Step: 27700... Loss: 1.2180... Val Loss: 1.4714
Epoch: 10/20... Step: 27710... Loss: 1.3300... Val Loss: 1.4740
Epoch: 10/20... Step: 27720... Loss: 1.4258... Val Loss: 1.4754
Epoch: 10/20... Step: 27730... Loss: 1.3839... Val Loss: 1.4735
Epoch: 10/20... Step: 27740... Loss: 1.4413... Val Loss: 1.4709
Epoch: 10/20... Step: 27750... Loss: 1.3508... Val Loss: 1.4722
Epoch: 10/20... Step: 27760... Loss: 1.2990... Val Loss: 1.4750
Epoch: 10/20... Step: 27770... Loss: 1.3906... Val Loss: 1.4743
Epoch: 10/20... Step: 27780... Loss: 1.3705... Val Loss: 1.4730
Epoch: 10/20... Step: 27790... Loss: 1.3

Epoch: 11/20... Step: 28930... Loss: 1.3851... Val Loss: 1.4721
Epoch: 11/20... Step: 28940... Loss: 1.3918... Val Loss: 1.4702
Epoch: 11/20... Step: 28950... Loss: 1.3706... Val Loss: 1.4714
Epoch: 11/20... Step: 28960... Loss: 1.3169... Val Loss: 1.4691
Epoch: 11/20... Step: 28970... Loss: 1.2333... Val Loss: 1.4683
Epoch: 11/20... Step: 28980... Loss: 1.3745... Val Loss: 1.4697
Epoch: 11/20... Step: 28990... Loss: 1.4121... Val Loss: 1.4709
Epoch: 11/20... Step: 29000... Loss: 1.2889... Val Loss: 1.4694
Epoch: 11/20... Step: 29010... Loss: 1.3755... Val Loss: 1.4704
Epoch: 11/20... Step: 29020... Loss: 1.2940... Val Loss: 1.4727
Epoch: 11/20... Step: 29030... Loss: 1.3535... Val Loss: 1.4722
Epoch: 11/20... Step: 29040... Loss: 1.3285... Val Loss: 1.4730
Epoch: 11/20... Step: 29050... Loss: 1.3328... Val Loss: 1.4736
Epoch: 11/20... Step: 29060... Loss: 1.3869... Val Loss: 1.4743
Epoch: 11/20... Step: 29070... Loss: 1.3690... Val Loss: 1.4730
Epoch: 11/20... Step: 29080... Loss: 1.1

Epoch: 11/20... Step: 30220... Loss: 1.2393... Val Loss: 1.4709
Epoch: 11/20... Step: 30230... Loss: 1.3901... Val Loss: 1.4687
Epoch: 11/20... Step: 30240... Loss: 1.4269... Val Loss: 1.4691
Epoch: 11/20... Step: 30250... Loss: 1.3382... Val Loss: 1.4732
Epoch: 11/20... Step: 30260... Loss: 1.3590... Val Loss: 1.4725
Epoch: 11/20... Step: 30270... Loss: 1.3624... Val Loss: 1.4726
Epoch: 11/20... Step: 30280... Loss: 1.2937... Val Loss: 1.4677
Epoch: 11/20... Step: 30290... Loss: 1.2997... Val Loss: 1.4692
Epoch: 11/20... Step: 30300... Loss: 1.3387... Val Loss: 1.4717
Epoch: 11/20... Step: 30310... Loss: 1.4957... Val Loss: 1.4686
Epoch: 11/20... Step: 30320... Loss: 1.3289... Val Loss: 1.4671
Epoch: 11/20... Step: 30330... Loss: 1.2989... Val Loss: 1.4709
Epoch: 11/20... Step: 30340... Loss: 1.2927... Val Loss: 1.4706
Epoch: 11/20... Step: 30350... Loss: 1.1811... Val Loss: 1.4668
Epoch: 11/20... Step: 30360... Loss: 1.3121... Val Loss: 1.4663
Epoch: 11/20... Step: 30370... Loss: 1.4

Epoch: 12/20... Step: 31510... Loss: 1.4169... Val Loss: 1.4633
Epoch: 12/20... Step: 31520... Loss: 1.2795... Val Loss: 1.4613
Epoch: 12/20... Step: 31530... Loss: 1.4608... Val Loss: 1.4622
Epoch: 12/20... Step: 31540... Loss: 1.3648... Val Loss: 1.4633
Epoch: 12/20... Step: 31550... Loss: 1.4240... Val Loss: 1.4713
Epoch: 12/20... Step: 31560... Loss: 1.3964... Val Loss: 1.4648
Epoch: 12/20... Step: 31570... Loss: 1.3804... Val Loss: 1.4631
Epoch: 12/20... Step: 31580... Loss: 1.4143... Val Loss: 1.4616
Epoch: 12/20... Step: 31590... Loss: 1.3687... Val Loss: 1.4610
Epoch: 12/20... Step: 31600... Loss: 1.3647... Val Loss: 1.4625
Epoch: 12/20... Step: 31610... Loss: 1.3601... Val Loss: 1.4629
Epoch: 12/20... Step: 31620... Loss: 1.3431... Val Loss: 1.4633
Epoch: 12/20... Step: 31630... Loss: 1.3353... Val Loss: 1.4662
Epoch: 12/20... Step: 31640... Loss: 1.4782... Val Loss: 1.4671
Epoch: 12/20... Step: 31650... Loss: 1.3125... Val Loss: 1.4654
Epoch: 12/20... Step: 31660... Loss: 1.5

Epoch: 12/20... Step: 32800... Loss: 1.3331... Val Loss: 1.4661
Epoch: 12/20... Step: 32810... Loss: 1.4073... Val Loss: 1.4639
Epoch: 12/20... Step: 32820... Loss: 1.3708... Val Loss: 1.4628
Epoch: 12/20... Step: 32830... Loss: 1.2998... Val Loss: 1.4642
Epoch: 12/20... Step: 32840... Loss: 1.2790... Val Loss: 1.4672
Epoch: 12/20... Step: 32850... Loss: 1.3470... Val Loss: 1.4668
Epoch: 12/20... Step: 32860... Loss: 1.4051... Val Loss: 1.4668
Epoch: 12/20... Step: 32870... Loss: 1.3109... Val Loss: 1.4647
Epoch: 12/20... Step: 32880... Loss: 1.4363... Val Loss: 1.4641
Epoch: 12/20... Step: 32890... Loss: 1.3555... Val Loss: 1.4658
Epoch: 12/20... Step: 32900... Loss: 1.3480... Val Loss: 1.4626
Epoch: 12/20... Step: 32910... Loss: 1.3885... Val Loss: 1.4620
Epoch: 12/20... Step: 32920... Loss: 1.4585... Val Loss: 1.4648
Epoch: 12/20... Step: 32930... Loss: 1.3088... Val Loss: 1.4645
Epoch: 12/20... Step: 32940... Loss: 1.2956... Val Loss: 1.4648
Epoch: 12/20... Step: 32950... Loss: 1.3

Epoch: 13/20... Step: 34090... Loss: 1.3871... Val Loss: 1.4617
Epoch: 13/20... Step: 34100... Loss: 1.2604... Val Loss: 1.4627
Epoch: 13/20... Step: 34110... Loss: 1.3165... Val Loss: 1.4607
Epoch: 13/20... Step: 34120... Loss: 1.3322... Val Loss: 1.4612
Epoch: 13/20... Step: 34130... Loss: 1.4055... Val Loss: 1.4626
Epoch: 13/20... Step: 34140... Loss: 1.3528... Val Loss: 1.4629
Epoch: 13/20... Step: 34150... Loss: 1.3102... Val Loss: 1.4626
Epoch: 13/20... Step: 34160... Loss: 1.2956... Val Loss: 1.4619
Epoch: 13/20... Step: 34170... Loss: 1.4078... Val Loss: 1.4613
Epoch: 13/20... Step: 34180... Loss: 1.3729... Val Loss: 1.4627
Epoch: 13/20... Step: 34190... Loss: 1.3860... Val Loss: 1.4603
Epoch: 13/20... Step: 34200... Loss: 1.2807... Val Loss: 1.4622
Epoch: 13/20... Step: 34210... Loss: 1.2995... Val Loss: 1.4628
Epoch: 13/20... Step: 34220... Loss: 1.3477... Val Loss: 1.4622
Epoch: 13/20... Step: 34230... Loss: 1.3906... Val Loss: 1.4600
Epoch: 13/20... Step: 34240... Loss: 1.2

Epoch: 13/20... Step: 35380... Loss: 1.2840... Val Loss: 1.4580
Epoch: 13/20... Step: 35390... Loss: 1.2477... Val Loss: 1.4577
Epoch: 13/20... Step: 35400... Loss: 1.3477... Val Loss: 1.4561
Epoch: 13/20... Step: 35410... Loss: 1.4330... Val Loss: 1.4585
Epoch: 13/20... Step: 35420... Loss: 1.3069... Val Loss: 1.4584
Epoch: 13/20... Step: 35430... Loss: 1.3269... Val Loss: 1.4587
Epoch: 13/20... Step: 35440... Loss: 1.3264... Val Loss: 1.4613
Epoch: 13/20... Step: 35450... Loss: 1.3140... Val Loss: 1.4613
Epoch: 13/20... Step: 35460... Loss: 1.3300... Val Loss: 1.4623
Epoch: 13/20... Step: 35470... Loss: 1.3283... Val Loss: 1.4646
Epoch: 13/20... Step: 35480... Loss: 1.4031... Val Loss: 1.4639
Epoch: 13/20... Step: 35490... Loss: 1.2716... Val Loss: 1.4638
Epoch: 13/20... Step: 35500... Loss: 1.2805... Val Loss: 1.4591
Epoch: 13/20... Step: 35510... Loss: 1.2236... Val Loss: 1.4598
Epoch: 13/20... Step: 35520... Loss: 1.2992... Val Loss: 1.4596
Epoch: 13/20... Step: 35530... Loss: 1.3

Epoch: 14/20... Step: 36670... Loss: 1.2688... Val Loss: 1.4634
Epoch: 14/20... Step: 36680... Loss: 1.4199... Val Loss: 1.4571
Epoch: 14/20... Step: 36690... Loss: 1.2796... Val Loss: 1.4553
Epoch: 14/20... Step: 36700... Loss: 1.3328... Val Loss: 1.4561
Epoch: 14/20... Step: 36710... Loss: 1.3138... Val Loss: 1.4568
Epoch: 14/20... Step: 36720... Loss: 1.3082... Val Loss: 1.4561
Epoch: 14/20... Step: 36730... Loss: 1.4596... Val Loss: 1.4563
Epoch: 14/20... Step: 36740... Loss: 1.4081... Val Loss: 1.4556
Epoch: 14/20... Step: 36750... Loss: 1.3101... Val Loss: 1.4533
Epoch: 14/20... Step: 36760... Loss: 1.3867... Val Loss: 1.4535
Epoch: 14/20... Step: 36770... Loss: 1.3783... Val Loss: 1.4556
Epoch: 14/20... Step: 36780... Loss: 1.2402... Val Loss: 1.4562
Epoch: 14/20... Step: 36790... Loss: 1.2300... Val Loss: 1.4583
Epoch: 14/20... Step: 36800... Loss: 1.3530... Val Loss: 1.4578
Epoch: 14/20... Step: 36810... Loss: 1.3713... Val Loss: 1.4571
Epoch: 14/20... Step: 36820... Loss: 1.3

Epoch: 14/20... Step: 37960... Loss: 1.4147... Val Loss: 1.4592
Epoch: 14/20... Step: 37970... Loss: 1.3969... Val Loss: 1.4608
Epoch: 14/20... Step: 37980... Loss: 1.4555... Val Loss: 1.4579
Epoch: 14/20... Step: 37990... Loss: 1.3617... Val Loss: 1.4570
Epoch: 14/20... Step: 38000... Loss: 1.3699... Val Loss: 1.4570
Epoch: 14/20... Step: 38010... Loss: 1.3272... Val Loss: 1.4529
Epoch: 14/20... Step: 38020... Loss: 1.3464... Val Loss: 1.4531
Epoch: 14/20... Step: 38030... Loss: 1.2668... Val Loss: 1.4539
Epoch: 14/20... Step: 38040... Loss: 1.3142... Val Loss: 1.4552
Epoch: 14/20... Step: 38050... Loss: 1.3418... Val Loss: 1.4568
Epoch: 14/20... Step: 38060... Loss: 1.3540... Val Loss: 1.4597
Epoch: 14/20... Step: 38070... Loss: 1.2735... Val Loss: 1.4567
Epoch: 14/20... Step: 38080... Loss: 1.3264... Val Loss: 1.4554
Epoch: 14/20... Step: 38090... Loss: 1.3959... Val Loss: 1.4528
Epoch: 14/20... Step: 38100... Loss: 1.3053... Val Loss: 1.4523
Epoch: 14/20... Step: 38110... Loss: 1.3

Epoch: 15/20... Step: 39250... Loss: 1.4258... Val Loss: 1.4516
Epoch: 15/20... Step: 39260... Loss: 1.3539... Val Loss: 1.4509
Epoch: 15/20... Step: 39270... Loss: 1.2991... Val Loss: 1.4516
Epoch: 15/20... Step: 39280... Loss: 1.2852... Val Loss: 1.4548
Epoch: 15/20... Step: 39290... Loss: 1.3146... Val Loss: 1.4559
Epoch: 15/20... Step: 39300... Loss: 1.3742... Val Loss: 1.4545
Epoch: 15/20... Step: 39310... Loss: 1.2659... Val Loss: 1.4531
Epoch: 15/20... Step: 39320... Loss: 1.4011... Val Loss: 1.4526
Epoch: 15/20... Step: 39330... Loss: 1.3137... Val Loss: 1.4513
Epoch: 15/20... Step: 39340... Loss: 1.3094... Val Loss: 1.4507
Epoch: 15/20... Step: 39350... Loss: 1.3869... Val Loss: 1.4523
Epoch: 15/20... Step: 39360... Loss: 1.2296... Val Loss: 1.4543
Epoch: 15/20... Step: 39370... Loss: 1.3044... Val Loss: 1.4531
Epoch: 15/20... Step: 39380... Loss: 1.2018... Val Loss: 1.4545
Epoch: 15/20... Step: 39390... Loss: 1.5244... Val Loss: 1.4571
Epoch: 15/20... Step: 39400... Loss: 1.3

Epoch: 15/20... Step: 40540... Loss: 1.3221... Val Loss: 1.4544
Epoch: 15/20... Step: 40550... Loss: 1.3903... Val Loss: 1.4521
Epoch: 15/20... Step: 40560... Loss: 1.2766... Val Loss: 1.4518
Epoch: 15/20... Step: 40570... Loss: 1.1439... Val Loss: 1.4528
Epoch: 15/20... Step: 40580... Loss: 1.4008... Val Loss: 1.4550
Epoch: 15/20... Step: 40590... Loss: 1.3292... Val Loss: 1.4531
Epoch: 15/20... Step: 40600... Loss: 1.3438... Val Loss: 1.4514
Epoch: 15/20... Step: 40610... Loss: 1.3289... Val Loss: 1.4526
Epoch: 15/20... Step: 40620... Loss: 1.3052... Val Loss: 1.4541
Epoch: 15/20... Step: 40630... Loss: 1.3415... Val Loss: 1.4525
Epoch: 15/20... Step: 40640... Loss: 1.3498... Val Loss: 1.4565
Epoch: 15/20... Step: 40650... Loss: 1.3735... Val Loss: 1.4560
Epoch: 15/20... Step: 40660... Loss: 1.2471... Val Loss: 1.4537
Epoch: 15/20... Step: 40670... Loss: 1.3489... Val Loss: 1.4534
Epoch: 15/20... Step: 40680... Loss: 1.3152... Val Loss: 1.4545
Epoch: 15/20... Step: 40690... Loss: 1.2

Epoch: 15/20... Step: 41830... Loss: 1.2635... Val Loss: 1.4508
Epoch: 15/20... Step: 41840... Loss: 1.4079... Val Loss: 1.4501
Epoch: 15/20... Step: 41850... Loss: 1.2630... Val Loss: 1.4499
Epoch: 15/20... Step: 41860... Loss: 1.3562... Val Loss: 1.4497
Epoch: 16/20... Step: 41870... Loss: 1.4392... Val Loss: 1.4500
Epoch: 16/20... Step: 41880... Loss: 1.3106... Val Loss: 1.4551
Epoch: 16/20... Step: 41890... Loss: 1.3943... Val Loss: 1.4504
Epoch: 16/20... Step: 41900... Loss: 1.2868... Val Loss: 1.4500
Epoch: 16/20... Step: 41910... Loss: 1.3553... Val Loss: 1.4508
Epoch: 16/20... Step: 41920... Loss: 1.3378... Val Loss: 1.4523
Epoch: 16/20... Step: 41930... Loss: 1.3499... Val Loss: 1.4527
Epoch: 16/20... Step: 41940... Loss: 1.2513... Val Loss: 1.4557
Epoch: 16/20... Step: 41950... Loss: 1.3431... Val Loss: 1.4534
Epoch: 16/20... Step: 41960... Loss: 1.3527... Val Loss: 1.4525
Epoch: 16/20... Step: 41970... Loss: 1.2935... Val Loss: 1.4530
Epoch: 16/20... Step: 41980... Loss: 1.2

Epoch: 16/20... Step: 43120... Loss: 1.2378... Val Loss: 1.4502
Epoch: 16/20... Step: 43130... Loss: 1.4462... Val Loss: 1.4511
Epoch: 16/20... Step: 43140... Loss: 1.2578... Val Loss: 1.4509
Epoch: 16/20... Step: 43150... Loss: 1.3301... Val Loss: 1.4497
Epoch: 16/20... Step: 43160... Loss: 1.2459... Val Loss: 1.4514
Epoch: 16/20... Step: 43170... Loss: 1.2791... Val Loss: 1.4504
Epoch: 16/20... Step: 43180... Loss: 1.3785... Val Loss: 1.4529
Epoch: 16/20... Step: 43190... Loss: 1.2317... Val Loss: 1.4536
Epoch: 16/20... Step: 43200... Loss: 1.2983... Val Loss: 1.4536
Epoch: 16/20... Step: 43210... Loss: 1.2565... Val Loss: 1.4525
Epoch: 16/20... Step: 43220... Loss: 1.2759... Val Loss: 1.4494
Epoch: 16/20... Step: 43230... Loss: 1.2428... Val Loss: 1.4484
Epoch: 16/20... Step: 43240... Loss: 1.3300... Val Loss: 1.4505
Epoch: 16/20... Step: 43250... Loss: 1.4821... Val Loss: 1.4520
Epoch: 16/20... Step: 43260... Loss: 1.2976... Val Loss: 1.4487
Epoch: 16/20... Step: 43270... Loss: 1.4

Epoch: 16/20... Step: 44410... Loss: 1.3648... Val Loss: 1.4472
Epoch: 16/20... Step: 44420... Loss: 1.2838... Val Loss: 1.4489
Epoch: 16/20... Step: 44430... Loss: 1.2825... Val Loss: 1.4488
Epoch: 16/20... Step: 44440... Loss: 1.3481... Val Loss: 1.4474
Epoch: 16/20... Step: 44450... Loss: 1.2795... Val Loss: 1.4480
Epoch: 16/20... Step: 44460... Loss: 1.4119... Val Loss: 1.4482
Epoch: 16/20... Step: 44470... Loss: 1.2647... Val Loss: 1.4499
Epoch: 16/20... Step: 44480... Loss: 1.3951... Val Loss: 1.4521
Epoch: 16/20... Step: 44490... Loss: 1.3263... Val Loss: 1.4487
Epoch: 16/20... Step: 44500... Loss: 1.2896... Val Loss: 1.4511
Epoch: 16/20... Step: 44510... Loss: 1.2569... Val Loss: 1.4501
Epoch: 16/20... Step: 44520... Loss: 1.3650... Val Loss: 1.4488
Epoch: 16/20... Step: 44530... Loss: 1.2810... Val Loss: 1.4487
Epoch: 16/20... Step: 44540... Loss: 1.3763... Val Loss: 1.4518
Epoch: 16/20... Step: 44550... Loss: 1.3884... Val Loss: 1.4478
Epoch: 16/20... Step: 44560... Loss: 1.2

Epoch: 17/20... Step: 45700... Loss: 1.3866... Val Loss: 1.4487
Epoch: 17/20... Step: 45710... Loss: 1.3224... Val Loss: 1.4472
Epoch: 17/20... Step: 45720... Loss: 1.3136... Val Loss: 1.4468
Epoch: 17/20... Step: 45730... Loss: 1.2953... Val Loss: 1.4484
Epoch: 17/20... Step: 45740... Loss: 1.2598... Val Loss: 1.4485
Epoch: 17/20... Step: 45750... Loss: 1.2065... Val Loss: 1.4457
Epoch: 17/20... Step: 45760... Loss: 1.1962... Val Loss: 1.4485
Epoch: 17/20... Step: 45770... Loss: 1.2500... Val Loss: 1.4487
Epoch: 17/20... Step: 45780... Loss: 1.1700... Val Loss: 1.4479
Epoch: 17/20... Step: 45790... Loss: 1.5009... Val Loss: 1.4495
Epoch: 17/20... Step: 45800... Loss: 1.3425... Val Loss: 1.4475
Epoch: 17/20... Step: 45810... Loss: 1.2883... Val Loss: 1.4501
Epoch: 17/20... Step: 45820... Loss: 1.3608... Val Loss: 1.4495
Epoch: 17/20... Step: 45830... Loss: 1.2995... Val Loss: 1.4480
Epoch: 17/20... Step: 45840... Loss: 1.2814... Val Loss: 1.4464
Epoch: 17/20... Step: 45850... Loss: 1.2

Epoch: 17/20... Step: 46990... Loss: 1.2881... Val Loss: 1.4452
Epoch: 17/20... Step: 47000... Loss: 1.3019... Val Loss: 1.4470
Epoch: 17/20... Step: 47010... Loss: 1.2853... Val Loss: 1.4490
Epoch: 17/20... Step: 47020... Loss: 1.2806... Val Loss: 1.4485
Epoch: 17/20... Step: 47030... Loss: 1.2366... Val Loss: 1.4457
Epoch: 17/20... Step: 47040... Loss: 1.2855... Val Loss: 1.4491
Epoch: 17/20... Step: 47050... Loss: 1.3019... Val Loss: 1.4484
Epoch: 17/20... Step: 47060... Loss: 1.3224... Val Loss: 1.4455
Epoch: 17/20... Step: 47070... Loss: 1.3623... Val Loss: 1.4464
Epoch: 17/20... Step: 47080... Loss: 1.2247... Val Loss: 1.4473
Epoch: 17/20... Step: 47090... Loss: 1.2909... Val Loss: 1.4493
Epoch: 17/20... Step: 47100... Loss: 1.4095... Val Loss: 1.4477
Epoch: 17/20... Step: 47110... Loss: 1.2899... Val Loss: 1.4489
Epoch: 17/20... Step: 47120... Loss: 1.4582... Val Loss: 1.4534
Epoch: 17/20... Step: 47130... Loss: 1.3695... Val Loss: 1.4528
Epoch: 17/20... Step: 47140... Loss: 1.4

Epoch: 18/20... Step: 48280... Loss: 1.3369... Val Loss: 1.4431
Epoch: 18/20... Step: 48290... Loss: 1.2764... Val Loss: 1.4445
Epoch: 18/20... Step: 48300... Loss: 1.3234... Val Loss: 1.4497
Epoch: 18/20... Step: 48310... Loss: 1.3344... Val Loss: 1.4426
Epoch: 18/20... Step: 48320... Loss: 1.3895... Val Loss: 1.4452
Epoch: 18/20... Step: 48330... Loss: 1.3107... Val Loss: 1.4447
Epoch: 18/20... Step: 48340... Loss: 1.3566... Val Loss: 1.4455
Epoch: 18/20... Step: 48350... Loss: 1.1727... Val Loss: 1.4449
Epoch: 18/20... Step: 48360... Loss: 1.2217... Val Loss: 1.4443
Epoch: 18/20... Step: 48370... Loss: 1.2423... Val Loss: 1.4462
Epoch: 18/20... Step: 48380... Loss: 1.2331... Val Loss: 1.4464
Epoch: 18/20... Step: 48390... Loss: 1.3764... Val Loss: 1.4445
Epoch: 18/20... Step: 48400... Loss: 1.2791... Val Loss: 1.4476
Epoch: 18/20... Step: 48410... Loss: 1.4051... Val Loss: 1.4474
Epoch: 18/20... Step: 48420... Loss: 1.2255... Val Loss: 1.4471
Epoch: 18/20... Step: 48430... Loss: 1.3

Epoch: 18/20... Step: 49570... Loss: 1.3580... Val Loss: 1.4435
Epoch: 18/20... Step: 49580... Loss: 1.2785... Val Loss: 1.4477
Epoch: 18/20... Step: 49590... Loss: 1.2803... Val Loss: 1.4480
Epoch: 18/20... Step: 49600... Loss: 1.3338... Val Loss: 1.4470
Epoch: 18/20... Step: 49610... Loss: 1.3308... Val Loss: 1.4460
Epoch: 18/20... Step: 49620... Loss: 1.3837... Val Loss: 1.4462
Epoch: 18/20... Step: 49630... Loss: 1.2553... Val Loss: 1.4446
Epoch: 18/20... Step: 49640... Loss: 1.4431... Val Loss: 1.4438
Epoch: 18/20... Step: 49650... Loss: 1.3377... Val Loss: 1.4408
Epoch: 18/20... Step: 49660... Loss: 1.2893... Val Loss: 1.4408
Epoch: 18/20... Step: 49670... Loss: 1.2621... Val Loss: 1.4422
Epoch: 18/20... Step: 49680... Loss: 1.3215... Val Loss: 1.4426
Epoch: 18/20... Step: 49690... Loss: 1.2957... Val Loss: 1.4423
Epoch: 18/20... Step: 49700... Loss: 1.3098... Val Loss: 1.4445
Epoch: 18/20... Step: 49710... Loss: 1.3348... Val Loss: 1.4436
Epoch: 18/20... Step: 49720... Loss: 1.2

Epoch: 19/20... Step: 50860... Loss: 1.5142... Val Loss: 1.4429
Epoch: 19/20... Step: 50870... Loss: 1.2043... Val Loss: 1.4444
Epoch: 19/20... Step: 50880... Loss: 1.3808... Val Loss: 1.4468
Epoch: 19/20... Step: 50890... Loss: 1.2855... Val Loss: 1.4473
Epoch: 19/20... Step: 50900... Loss: 1.2997... Val Loss: 1.4473
Epoch: 19/20... Step: 50910... Loss: 1.3521... Val Loss: 1.4446
Epoch: 19/20... Step: 50920... Loss: 1.2660... Val Loss: 1.4447
Epoch: 19/20... Step: 50930... Loss: 1.3250... Val Loss: 1.4454
Epoch: 19/20... Step: 50940... Loss: 1.3071... Val Loss: 1.4447
Epoch: 19/20... Step: 50950... Loss: 1.2414... Val Loss: 1.4514
Epoch: 19/20... Step: 50960... Loss: 1.2826... Val Loss: 1.4446
Epoch: 19/20... Step: 50970... Loss: 1.3247... Val Loss: 1.4429
Epoch: 19/20... Step: 50980... Loss: 1.3512... Val Loss: 1.4411
Epoch: 19/20... Step: 50990... Loss: 1.1592... Val Loss: 1.4409
Epoch: 19/20... Step: 51000... Loss: 1.1837... Val Loss: 1.4441
Epoch: 19/20... Step: 51010... Loss: 1.1

Epoch: 19/20... Step: 52150... Loss: 1.2496... Val Loss: 1.4416
Epoch: 19/20... Step: 52160... Loss: 1.3745... Val Loss: 1.4426
Epoch: 19/20... Step: 52170... Loss: 1.3062... Val Loss: 1.4428
Epoch: 19/20... Step: 52180... Loss: 1.2535... Val Loss: 1.4411
Epoch: 19/20... Step: 52190... Loss: 1.2585... Val Loss: 1.4453
Epoch: 19/20... Step: 52200... Loss: 1.2094... Val Loss: 1.4440
Epoch: 19/20... Step: 52210... Loss: 1.3010... Val Loss: 1.4442
Epoch: 19/20... Step: 52220... Loss: 1.4016... Val Loss: 1.4432
Epoch: 19/20... Step: 52230... Loss: 1.3020... Val Loss: 1.4435
Epoch: 19/20... Step: 52240... Loss: 1.3571... Val Loss: 1.4413
Epoch: 19/20... Step: 52250... Loss: 1.3562... Val Loss: 1.4425
Epoch: 19/20... Step: 52260... Loss: 1.2706... Val Loss: 1.4429
Epoch: 19/20... Step: 52270... Loss: 1.2604... Val Loss: 1.4420
Epoch: 19/20... Step: 52280... Loss: 1.3445... Val Loss: 1.4441
Epoch: 19/20... Step: 52290... Loss: 1.2792... Val Loss: 1.4472
Epoch: 19/20... Step: 52300... Loss: 1.3

Epoch: 20/20... Step: 53440... Loss: 1.3211... Val Loss: 1.4416
Epoch: 20/20... Step: 53450... Loss: 1.3589... Val Loss: 1.4404
Epoch: 20/20... Step: 53460... Loss: 1.2541... Val Loss: 1.4402
Epoch: 20/20... Step: 53470... Loss: 1.2300... Val Loss: 1.4413
Epoch: 20/20... Step: 53480... Loss: 1.3427... Val Loss: 1.4419
Epoch: 20/20... Step: 53490... Loss: 1.3345... Val Loss: 1.4388
Epoch: 20/20... Step: 53500... Loss: 1.2934... Val Loss: 1.4390
Epoch: 20/20... Step: 53510... Loss: 1.3365... Val Loss: 1.4403
Epoch: 20/20... Step: 53520... Loss: 1.2056... Val Loss: 1.4397
Epoch: 20/20... Step: 53530... Loss: 1.2725... Val Loss: 1.4404
Epoch: 20/20... Step: 53540... Loss: 1.3420... Val Loss: 1.4409
Epoch: 20/20... Step: 53550... Loss: 1.2934... Val Loss: 1.4420
Epoch: 20/20... Step: 53560... Loss: 1.3220... Val Loss: 1.4394
Epoch: 20/20... Step: 53570... Loss: 1.2907... Val Loss: 1.4407
Epoch: 20/20... Step: 53580... Loss: 1.2446... Val Loss: 1.4401
Epoch: 20/20... Step: 53590... Loss: 1.1

Epoch: 20/20... Step: 54730... Loss: 1.2782... Val Loss: 1.4393
Epoch: 20/20... Step: 54740... Loss: 1.3921... Val Loss: 1.4384
Epoch: 20/20... Step: 54750... Loss: 1.3135... Val Loss: 1.4375
Epoch: 20/20... Step: 54760... Loss: 1.3743... Val Loss: 1.4359
Epoch: 20/20... Step: 54770... Loss: 1.2413... Val Loss: 1.4377
Epoch: 20/20... Step: 54780... Loss: 1.2935... Val Loss: 1.4363
Epoch: 20/20... Step: 54790... Loss: 1.3751... Val Loss: 1.4355
Epoch: 20/20... Step: 54800... Loss: 1.2638... Val Loss: 1.4402
Epoch: 20/20... Step: 54810... Loss: 1.2521... Val Loss: 1.4407
Epoch: 20/20... Step: 54820... Loss: 1.4415... Val Loss: 1.4397
Epoch: 20/20... Step: 54830... Loss: 1.2714... Val Loss: 1.4382
Epoch: 20/20... Step: 54840... Loss: 1.2599... Val Loss: 1.4374
Epoch: 20/20... Step: 54850... Loss: 1.2915... Val Loss: 1.4388
Epoch: 20/20... Step: 54860... Loss: 1.3086... Val Loss: 1.4383
Epoch: 20/20... Step: 54870... Loss: 1.2166... Val Loss: 1.4382
Epoch: 20/20... Step: 54880... Loss: 1.2

## Getting the best model

To set your hyperparameters to get the best performance, you'll want to watch the training and validation losses. If your training loss is much lower than the validation loss, you're overfitting. Increase regularization (more dropout) or use a smaller network. If the training and validation losses are close, you're underfitting so you can increase the size of the network.

## Hyperparameters

Here are the hyperparameters for the network.

In defining the model:
* `n_hidden` - The number of units in the hidden layers.
* `n_layers` - Number of hidden LSTM layers to use.

We assume that dropout probability and learning rate will be kept at the default, in this example.

And in training:
* `batch_size` - Number of sequences running through the network in one pass.
* `seq_length` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lr` - Learning rate for training

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `n_hidden` and `n_layers`. I would advise that you always use `n_layers` of either 2/3. The `n_hidden` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `n_hidden` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

## Checkpoint

After training, we'll save the model so we can load it again later if we need too. Here I'm saving the parameters needed to create the same architecture, the hidden layer hyperparameters and the text characters.

In [21]:
# change the name, for saving multiple files
model_name = '../../saved_models/rnn_2_epoch.net'

checkpoint = {'n_hidden': net.n_hidden,
              'n_layers': net.n_layers,
              'state_dict': net.state_dict(),
              'tokens': net.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)

---
## Making Predictions

Now that the model is trained, we'll want to sample from it and make predictions about next characters! To sample, we pass in a character and have the network predict the next character. Then we take that character, pass it back in, and get another predicted character. Just keep doing this and you'll generate a bunch of text!

### A note on the `predict`  function

The output of our RNN is from a fully-connected layer and it outputs a **distribution of next-character scores**.

> To actually get the next character, we apply a softmax function, which gives us a *probability* distribution that we can then sample to predict the next character.

### Top K sampling

Our predictions come from a categorical probability distribution over all the possible characters. We can make the sample text and make it more reasonable to handle (with less variables) by only considering some $K$ most probable characters. This will prevent the network from giving us completely absurd characters while allowing it to introduce some noise and randomness into the sampled text. Read more about [topk, here](https://pytorch.org/docs/stable/torch.html#torch.topk).


In [22]:
def predict(net, char, h=None, top_k=None):
        ''' Given a character, predict the next character.
            Returns the predicted character and the hidden state.
        '''
        
        # tensor inputs
        x = np.array([[net.char2int[char]]])
        x = one_hot_encode(x, len(net.chars))
        inputs = torch.from_numpy(x)
        
        if(train_on_gpu):
            inputs = inputs.cuda()
        
        # detach hidden state from history
        h = tuple([each.data for each in h])
        # get the output of the model
        out, h = net(inputs, h)

        # get the character probabilities
        p = F.softmax(out, dim=1).data
        if(train_on_gpu):
            p = p.cpu() # move to cpu
        
        # get top characters
        if top_k is None:
            top_ch = np.arange(len(net.chars))
        else:
            p, top_ch = p.topk(top_k)
            top_ch = top_ch.numpy().squeeze()
        
        # select the likely next character with some element of randomness
        p = p.numpy().squeeze()
        char = np.random.choice(top_ch, p=p/p.sum())
        
        # return the encoded value of the predicted char and the hidden state
        return net.int2char[char], h

### Priming and generating text 

Typically you'll want to prime the network so you can build up a hidden state. Otherwise the network will start out generating characters at random. In general the first bunch of characters will be a little rough since it hasn't built up a long history of characters to predict from.

In [24]:
def sample(net, size, prime='The', top_k=None):
        
    if(train_on_gpu):
        net.cuda()
    else:
        net.cpu()
    
    net.eval() # eval mode
    
    # First off, run through the prime characters
    chars = [ch for ch in prime]
    h = net.init_hidden(1)
    for ch in prime:
        char, h = predict(net, ch, h, top_k=top_k)

    chars.append(char)
    
    # Now pass in the previous character and get a new one
    for ii in range(size):
        char, h = predict(net, chars[-1], h, top_k=top_k)
        chars.append(char)

    return ''.join(chars)

In [28]:
print(sample(net, 1000, prime='Anna said', top_k=5))

Anna said.

"A fancies who have you are completely."

"You meant to tenne, but I wanted, but I'm not thine on the children," he said,
wing to allow and some princess. "Yes, to go to that is think and so much it with his most thing."

"I have a month. The measures. That's not to think," turning this, and the propress to say the feeling on with spite
of
the country and talking to her for
their proffore in his
husbands attention in his watch
with a child. Hooding
her, and answered to
the last, and her
father's family, who had been
a principres of a smile that his face all the carping out with a pationable,
and stood
steps. "I am all my face?..." He said she howered at them. But his hind, and she walked the porter. The chief concession trees to see it, and he had so much. But strok that he was seeing her as
though she so lighted as a strange and threathers after a peasant, so that the conversations.
"We've care a picture," he said.

"A shoulder what you know it with any clans were say at t

## Loading a checkpoint

In [26]:
# Here we have loaded in a model that trained over 20 epochs `rnn_20_epoch.net`
with open('../../saved_models/rnn_2_epoch.net', 'rb') as f:
    checkpoint = torch.load(f)
    
loaded = CharRNN(checkpoint['tokens'], n_hidden=checkpoint['n_hidden'], n_layers=checkpoint['n_layers'])
loaded.load_state_dict(checkpoint['state_dict'])

<All keys matched successfully>

In [29]:
# Sample using a loaded model
print(sample(loaded, 2000, top_k=5, prime="And Levin said"))

And Levin said is happiness, that they wonked him. He cut his strange of the same wife and that, and, the fack with a little conversation.

"I can't leave you the sort."

"Well, and I didn't call it with all the men more and disapproved," said Stepan
Arkadyevitch was the mind over the same wife and humor to be supporting the friends in the carroa with the chord to the
matchions would have been to listen, when the feeling of the condition
of the farmer
on
the sacrs of the father.

"What as though though he had say no one thank yourself in them. And though I won't tell that," said the same things, before a man of a smiling, that he had to be
already standing her.

This
party as though it wanted to her and, and saw her heart and heart out all the strend, who, and she wanted at the porter and heart, began and cries with them or waiting trackly watching the same doing that she was clirking, and said would have all
strunging.

"I have succeeded this so much it, I cannot be a prince with a li

# Practice Arena

In [4]:
a= "amavs\ns s d"
print(set(a))

{'m', 's', 'v', '\n', 'd', 'a', ' '}


In [14]:
5//3

1